import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  daisyui: {
    themes: [
      {
        'sumi-light': {
          'primary': '#C0392B',
          'primary-content': '#F5F0E8',
          'secondary': '#C9A84C',
          'secondary-content': '#1A1A1A',
          'accent': '#C9A84C',
          'accent-content': '#1A1A1A',
          'neutral': '#1A1A1A',
          'neutral-content': '#F5F0E8',
          'base-100': '#F5F0E8',
          'base-200': '#E8E3DA',
          'base-300': '#D4CFC4',
          'base-content': '#1A1A1A',
          'info': '#4A6E8C',
          'info-content': '#F5F0E8',
          'success': '#2D6B3E',
          'success-content': '#F5F0E8',
          'warning': '#C9A84C',
          'warning-content': '#1A1A1A',
          'error': '#B73229',
          'error-content': '#F5F0E8',
          '--rounded-box': '4px',
          '--rounded-btn': '2px',
          '--rounded-badge': '2px',
          '--animation-btn': '0.2s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.97',
          '--tab-border': '1px',
          '--tab-radius': '2px',
        },
        'sumi-dark': {
          'primary': '#E85A4A',
          'primary-content': '#1A1A14',
          'secondary': '#D4B85C',
          'secondary-content': '#1A1A14',
          'accent': '#D4B85C',
          'accent-content': '#1A1A14',
          'neutral': '#E8E3DA',
          'neutral-content': '#1A1A14',
          'base-100': '#1A1A14',
          'base-200': '#2C2824',
          'base-300': '#3D3832',
          'base-content': '#E8E3DA',
          'info': '#7BA0C7',
          'info-content': '#1A1A14',
          'success': '#4A9E5E',
          'success-content': '#1A1A14',
          'warning': '#D4B85C',
          'warning-content': '#1A1A14',
          'error': '#E05541',
          'error-content': '#1A1A14',
          '--rounded-box': '4px',
          '--rounded-btn': '2px',
          '--rounded-badge': '2px',
          '--animation-btn': '0.2s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.97',
          '--tab-border': '1px',
          '--tab-radius': '2px',
        },
      },
    ],
  },
  theme: {
    extend: {
      colors: {
        sumi: 'rgb(var(--sumi-rgb) / <alpha-value>)',
        'sumi-deep': 'rgb(var(--sumi-deep-rgb) / <alpha-value>)',
        washi: 'rgb(var(--washi-rgb) / <alpha-value>)',
        'washi-light': 'rgb(var(--washi-light-rgb) / <alpha-value>)',
        'washi-medium': 'rgb(var(--washi-medium-rgb) / <alpha-value>)',
        vermillion: 'rgb(var(--vermillion-rgb) / <alpha-value>)',
        gold: 'rgb(var(--gold-rgb) / <alpha-value>)',
        mist: 'rgb(var(--mist-rgb) / <alpha-value>)',
        error: 'rgb(var(--error-rgb) / <alpha-value>)',
        success: 'rgb(var(--success-rgb) / <alpha-value>)',
        info: 'rgb(var(--info-rgb) / <alpha-value>)',
        'ink-wash': 'rgba(var(--sumi-rgb), 0.06)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'Georgia', 'serif'],
        'display-jp': ['var(--font-display-jp)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
        accent: ['var(--font-accent)', 'serif'],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        '30': '7.5rem',
      },
      borderRadius: {
        'ink': '2px',
        'ink-md': '4px',
        'ink-lg': '8px',
      },
      boxShadow: {
        'ink': '0 2px 8px rgba(26,26,26,0.15), 0 0 0 1px rgba(26,26,26,0.04)',
        'ink-sm': '0 1px 2px rgba(26,26,26,0.06)',
        'ink-md': '0 4px 12px rgba(26,26,26,0.08)',
        'ink-lg': '0 8px 24px rgba(26,26,26,0.10)',
      },
      transitionDuration: {
        'instant': '100ms',
        'fast': '200ms',
        'normal': '400ms',
        'slow': '800ms',
        'deliberate': '1200ms',
      },
      transitionTimingFunction: {
        'out-soft': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'in-out-soft': 'cubic-bezier(0.65, 0, 0.35, 1)',
        'ink-bleed': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'brush-stroke': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
      },
      keyframes: {
        'ink-spread': {
          '0%': { filter: 'blur(8px)', opacity: '0' },
          '100%': { filter: 'blur(0)', opacity: '1' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'ink-drip': {
          '0%': { height: '0%' },
          '100%': { height: '100%' },
        },
      },
      animation: {
        'ink-spread': 'ink-spread 1.2s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'float': 'float 6s ease-in-out infinite',
        'ink-drip': 'ink-drip 1s ease-out forwards',
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
}
export default config
