import type { Artwork } from '@/types'

export const FALLBACK_ARTWORKS: Artwork[] = [
  {
    id: 1,
    title: "Kinryūsan Temple at Asakusa, from the series \"One Hundred Famous Views of Edo\"",
    title_jp: '',
    series: 'One Hundred Famous Views of Edo' as const,
    series_number: 0,
    year: 1856,
    description: "Hiroshige depicts a sacred site with architectural precision and atmospheric depth, capturing both the spiritual significance and the daily life surrounding the temple grounds.",
    wikimedia_url: "/images/artworks/full/kinry-san-temple-at-asakusa-from-the-series-one-hundred-famous-views-of-edo.jpg",
    wikimedia_thumb: "/images/artworks/thumb/kinry-san-temple-at-asakusa-from-the-series-one-hundred-famous-views-of-edo.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/56689",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 1,
  },
  {
    id: 2,
    title: "“Azuma Bridge from Komagatadō Temple,” from the series One Hundred Famous Views of Edo (Meisho Edo hyakkei, Komagatadō Azumabashi)",
    title_jp: '',
    series: 'One Hundred Famous Views of Edo' as const,
    series_number: 0,
    year: 1857,
    description: "A bustling bridge scene from the Tōkaidō road, with travelers crossing over a wide river while the distant landscape unfolds in Hiroshige's signature atmospheric perspective.",
    wikimedia_url: "/images/artworks/full/azuma-bridge-from-komagatado-temple-from-the-series-one-hundred-famous-views-of-edo-meisho-edo-hyakkei-komagatado-azumabashi.jpg",
    wikimedia_thumb: "/images/artworks/thumb/azuma-bridge-from-komagatado-temple-from-the-series-one-hundred-famous-views-of-edo-meisho-edo-hyakkei-komagatado-azumabashi.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/37282",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 2,
  },
  {
    id: 3,
    title: "Sudden Shower over Shin-Ōhashi Bridge and Atake (Ōhashi Atake no yūdachi), from the series One Hundred Famous Views of Edo (Meisho Edo hyakkei)",
    title_jp: '',
    series: 'One Hundred Famous Views of Edo' as const,
    series_number: 0,
    year: 1857,
    description: "Hiroshige captures a sudden rain shower with bold diagonal lines and masterful use of negative space, transforming a transient weather moment into an enduring work of art.",
    wikimedia_url: "/images/artworks/full/sudden-shower-over-shin-ohashi-bridge-and-atake-ohashi-atake-no-y-dachi-from-the-series-one-hundred-famous-views-of-edo-meisho-edo-hyakkei.jpg",
    wikimedia_thumb: "/images/artworks/thumb/sudden-shower-over-shin-ohashi-bridge-and-atake-ohashi-atake-no-y-dachi-from-the-series-one-hundred-famous-views-of-edo-meisho-edo-hyakkei.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/55433",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 3,
  },
  {
    id: 4,
    title: "Revelers Returned from the Tori no Machi Festival at Asakusa, from the series One Hundred Famous Views of Edo",
    title_jp: '',
    series: 'One Hundred Famous Views of Edo' as const,
    series_number: 0,
    year: 1857,
    description: "The famous Sensō-ji temple at Asakusa, rendered in Hiroshige's distinctive style with meticulous architectural detail and a lively street scene in the foreground.",
    wikimedia_url: "/images/artworks/full/revelers-returned-from-the-tori-no-machi-festival-at-asakusa-from-the-series-one-hundred-famous-views-of-edo.jpg",
    wikimedia_thumb: "/images/artworks/thumb/revelers-returned-from-the-tori-no-machi-festival-at-asakusa-from-the-series-one-hundred-famous-views-of-edo.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36539",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 4,
  },
  {
    id: 5,
    title: "The Tanabata Festival, from the series One Hundred Famous Views of Edo",
    title_jp: '',
    series: 'One Hundred Famous Views of Edo' as const,
    series_number: 0,
    year: 1857,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/the-tanabata-festival-from-the-series-one-hundred-famous-views-of-edo.jpg",
    wikimedia_thumb: "/images/artworks/thumb/the-tanabata-festival-from-the-series-one-hundred-famous-views-of-edo.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36541",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 5,
  },
  {
    id: 6,
    title: "“Minowa, Kanasugi at Mikawashima,” from the series One Hundred Famous Views of Edo (Meisho Edo hyakkei, Minowa Kanasugi, Mikawashima)",
    title_jp: '',
    series: 'One Hundred Famous Views of Edo' as const,
    series_number: 0,
    year: 1857,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/minowa-kanasugi-at-mikawashima-from-the-series-one-hundred-famous-views-of-edo-meisho-edo-hyakkei-minowa-kanasugi-mikawashima.jpg",
    wikimedia_thumb: "/images/artworks/thumb/minowa-kanasugi-at-mikawashima-from-the-series-one-hundred-famous-views-of-edo-meisho-edo-hyakkei-minowa-kanasugi-mikawashima.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36542",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 6,
  },
  {
    id: 7,
    title: "Toto, Ryogoku, from the series Thirty-six Views of Mount Fuji (Fugaku sanjūrokkei)",
    title_jp: '',
    series: 'Thirty-six Views of Mount Fuji' as const,
    series_number: 0,
    year: 1858,
    description: "Mount Fuji rises majestically in the distance as travelers make their way along the Tōkaidō road, in one of Hiroshige's most celebrated landscape compositions.",
    wikimedia_url: "/images/artworks/full/toto-ryogoku-from-the-series-thirty-six-views-of-mount-fuji-fugaku-sanj-rokkei.jpg",
    wikimedia_thumb: "/images/artworks/thumb/toto-ryogoku-from-the-series-thirty-six-views-of-mount-fuji-fugaku-sanj-rokkei.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36536",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 7,
  },
  {
    id: 8,
    title: "View of Mount Fuji from Koshigaya, Province of Musashi (Musashi, Koshigaya Zai), from the series Thirty-six Views of Mount Fuji (Fugaku sanjūrokkei)",
    title_jp: '',
    series: 'Thirty-six Views of Mount Fuji' as const,
    series_number: 0,
    year: 1858,
    description: "Mount Fuji rises majestically in the distance as travelers make their way along the Tōkaidō road, in one of Hiroshige's most celebrated landscape compositions.",
    wikimedia_url: "/images/artworks/full/view-of-mount-fuji-from-koshigaya-province-of-musashi-musashi-koshigaya-zai-from-the-series-thirty-six-views-of-mount-fuji-fugaku-sanj-rokkei.jpg",
    wikimedia_thumb: "/images/artworks/thumb/view-of-mount-fuji-from-koshigaya-province-of-musashi-musashi-koshigaya-zai-from-the-series-thirty-six-views-of-mount-fuji-fugaku-sanj-rokkei.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36537",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 9,
    title: "View of Mount Fuji from Seven-ri Beach, Province of Sagami (Sōshū: Shichi-ri ga hama), from the series Thirty-six Views of Mount Fuji (Fugaku sanjūrokkei)",
    title_jp: '',
    series: 'Thirty-six Views of Mount Fuji' as const,
    series_number: 0,
    year: 1858,
    description: "Mount Fuji rises majestically in the distance as travelers make their way along the Tōkaidō road, in one of Hiroshige's most celebrated landscape compositions.",
    wikimedia_url: "/images/artworks/full/view-of-mount-fuji-from-seven-ri-beach-province-of-sagami-sosh-shichi-ri-ga-hama-from-the-series-thirty-six-views-of-mount-fuji-fugaku-sanj-rokkei.jpg",
    wikimedia_thumb: "/images/artworks/thumb/view-of-mount-fuji-from-seven-ri-beach-province-of-sagami-sosh-shichi-ri-ga-hama-from-the-series-thirty-six-views-of-mount-fuji-fugaku-sanj-rokkei.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36538",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 10,
    title: "The Kiso Mountains in Snow",
    title_jp: '',
    series: 'The Sixty-nine Stations of the Kisokaidō' as const,
    series_number: 0,
    year: 1857,
    description: "A serene winter scene captured in Hiroshige's masterful composition, with falling snow creating a quiet, atmospheric landscape that exemplifies the beauty of ukiyo-e printmaking.",
    wikimedia_url: "/images/artworks/full/the-kiso-mountains-in-snow.jpg",
    wikimedia_thumb: "/images/artworks/thumb/the-kiso-mountains-in-snow.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36545",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 11,
    title: "The Autumn Moon at Ishiyama on Lake Biwa",
    title_jp: '',
    series: 'Eight Views of Ōmi' as const,
    series_number: 0,
    year: 1835,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/the-autumn-moon-at-ishiyama-on-lake-biwa.jpg",
    wikimedia_thumb: "/images/artworks/thumb/the-autumn-moon-at-ishiyama-on-lake-biwa.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36527",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 12,
    title: "Seta no Sekisho. Sunset, Seta. Lake Biwa",
    title_jp: '',
    series: 'Eight Views of Ōmi' as const,
    series_number: 0,
    year: 1835,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/seta-no-sekisho-sunset-seta-lake-biwa.jpg",
    wikimedia_thumb: "/images/artworks/thumb/seta-no-sekisho-sunset-seta-lake-biwa.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36528",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 13,
    title: "Clearing Weather at Awazu, Lake Biwa",
    title_jp: '',
    series: 'Eight Views of Ōmi' as const,
    series_number: 0,
    year: 1835,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/clearing-weather-at-awazu-lake-biwa.jpg",
    wikimedia_thumb: "/images/artworks/thumb/clearing-weather-at-awazu-lake-biwa.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36529",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 14,
    title: "Geese Alighting at Katada, Lake Biwa",
    title_jp: '',
    series: 'Eight Views of Ōmi' as const,
    series_number: 0,
    year: 1835,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/geese-alighting-at-katada-lake-biwa.jpg",
    wikimedia_thumb: "/images/artworks/thumb/geese-alighting-at-katada-lake-biwa.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36530",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 15,
    title: "Night Rain at Karasaki, from the series Eight Views of Ōmi (Ōmi hakkei no uchi)",
    title_jp: '',
    series: 'Eight Views of Ōmi' as const,
    series_number: 0,
    year: 1835,
    description: "Hiroshige captures a sudden rain shower with bold diagonal lines and masterful use of negative space, transforming a transient weather moment into an enduring work of art.",
    wikimedia_url: "/images/artworks/full/night-rain-at-karasaki-from-the-series-eight-views-of-omi-omi-hakkei-no-uchi.jpg",
    wikimedia_thumb: "/images/artworks/thumb/night-rain-at-karasaki-from-the-series-eight-views-of-omi-omi-hakkei-no-uchi.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36531",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 16,
    title: "Station Thirty-Eight: Fujikawa, Scene at the Border, from the Fifty-Three Stations of the Tokaido",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1833,
    description: "Mount Fuji rises majestically in the distance as travelers make their way along the Tōkaidō road, in one of Hiroshige's most celebrated landscape compositions.",
    wikimedia_url: "/images/artworks/full/station-thirty-eight-fujikawa-scene-at-the-border-from-the-fifty-three-stations-of-the-tokaido.jpg",
    wikimedia_thumb: "/images/artworks/thumb/station-thirty-eight-fujikawa-scene-at-the-border-from-the-fifty-three-stations-of-the-tokaido.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/56906",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 17,
    title: "A Snowy Evening at Kanbara Station",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1833,
    description: "A serene winter scene captured in Hiroshige's masterful composition, with falling snow creating a quiet, atmospheric landscape that exemplifies the beauty of ukiyo-e printmaking.",
    wikimedia_url: "/images/artworks/full/a-snowy-evening-at-kanbara-station.jpg",
    wikimedia_thumb: "/images/artworks/thumb/a-snowy-evening-at-kanbara-station.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36937",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 18,
    title: "Evening Snow at Kanbara, from the series \"Fifty-three Stations of the Tōkaidō\"",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1833,
    description: "A serene winter scene captured in Hiroshige's masterful composition, with falling snow creating a quiet, atmospheric landscape that exemplifies the beauty of ukiyo-e printmaking.",
    wikimedia_url: "/images/artworks/full/evening-snow-at-kanbara-from-the-series-fifty-three-stations-of-the-tokaido.jpg",
    wikimedia_thumb: "/images/artworks/thumb/evening-snow-at-kanbara-from-the-series-fifty-three-stations-of-the-tokaido.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/56915",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 18,
  },
  {
    id: 19,
    title: "Morning Mist at Mishima",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1833,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/morning-mist-at-mishima.jpg",
    wikimedia_thumb: "/images/artworks/thumb/morning-mist-at-mishima.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36520",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 20,
    title: "Spring Rain at Tsuchiyama, from the series Fifty-three Stations of the Tōkaidō",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1834,
    description: "Hiroshige captures a sudden rain shower with bold diagonal lines and masterful use of negative space, transforming a transient weather moment into an enduring work of art.",
    wikimedia_url: "/images/artworks/full/spring-rain-at-tsuchiyama-from-the-series-fifty-three-stations-of-the-tokaido.jpg",
    wikimedia_thumb: "/images/artworks/thumb/spring-rain-at-tsuchiyama-from-the-series-fifty-three-stations-of-the-tokaido.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36971",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 20,
  },
  {
    id: 21,
    title: "Sudden Shower at Shōno, from the series Fifty-three Stations of the Tōkaidō",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1834,
    description: "Hiroshige captures a sudden rain shower with bold diagonal lines and masterful use of negative space, transforming a transient weather moment into an enduring work of art.",
    wikimedia_url: "/images/artworks/full/sudden-shower-at-shono-from-the-series-fifty-three-stations-of-the-tokaido.jpg",
    wikimedia_thumb: "/images/artworks/thumb/sudden-shower-at-shono-from-the-series-fifty-three-stations-of-the-tokaido.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36521",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: true,
    display_order: 21,
  },
  {
    id: 22,
    title: "Shinagawa Station",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A view of a post station along the Tōkaidō road, where travelers rest and resupply. The composition captures the rhythm of travel and the character of the station town.",
    wikimedia_url: "/images/artworks/full/shinagawa-station.jpg",
    wikimedia_thumb: "/images/artworks/thumb/shinagawa-station.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36546",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 23,
    title: "Kawasaki",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/kawasaki.jpg",
    wikimedia_thumb: "/images/artworks/thumb/kawasaki.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36547",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 24,
    title: "Kanagawa",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/kanagawa.jpg",
    wikimedia_thumb: "/images/artworks/thumb/kanagawa.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36548",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 25,
    title: "Hodogaya",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/hodogaya.jpg",
    wikimedia_thumb: "/images/artworks/thumb/hodogaya.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36549",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 26,
    title: "Totsuka",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/totsuka.jpg",
    wikimedia_thumb: "/images/artworks/thumb/totsuka.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36550",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 27,
    title: "Fujisawa",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "Mount Fuji rises majestically in the distance as travelers make their way along the Tōkaidō road, in one of Hiroshige's most celebrated landscape compositions.",
    wikimedia_url: "/images/artworks/full/fujisawa.jpg",
    wikimedia_thumb: "/images/artworks/thumb/fujisawa.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36551",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 28,
    title: "Hiratsuka",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/hiratsuka.jpg",
    wikimedia_thumb: "/images/artworks/thumb/hiratsuka.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36552",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 29,
    title: "Ōiso",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/oiso.jpg",
    wikimedia_thumb: "/images/artworks/thumb/oiso.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36553",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 30,
    title: "Odawara",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/odawara.jpg",
    wikimedia_thumb: "/images/artworks/thumb/odawara.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36554",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 31,
    title: "Hakone",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/hakone.jpg",
    wikimedia_thumb: "/images/artworks/thumb/hakone.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36555",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 32,
    title: "Mishima, from the series Fifty-three Stations of the Tōkaidō Road (Tōkaidō gojūsan tsugi, Mishima), also known as the Kyōka (Witty Verse) Tōkaidō",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A view of a post station along the Tōkaidō road, where travelers rest and resupply. The composition captures the rhythm of travel and the character of the station town.",
    wikimedia_url: "/images/artworks/full/mishima-from-the-series-fifty-three-stations-of-the-tokaido-road-tokaido-goj-san-tsugi-mishima-also-known-as-the-kyoka-witty-verse-tokaido.jpg",
    wikimedia_thumb: "/images/artworks/thumb/mishima-from-the-series-fifty-three-stations-of-the-tokaido-road-tokaido-goj-san-tsugi-mishima-also-known-as-the-kyoka-witty-verse-tokaido.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36556",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 33,
    title: "Numazu",
    title_jp: '',
    series: 'Fifty-Three Stations of the Tōkaidō' as const,
    series_number: 0,
    year: 1838,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/numazu.jpg",
    wikimedia_thumb: "/images/artworks/thumb/numazu.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36557",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 34,
    title: "Cherry Blossoms at Arashiyama, from the series Famous Places of Kyōto",
    title_jp: '',
    series: 'Famous Places of Kyōto' as const,
    series_number: 0,
    year: 1834,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/cherry-blossoms-at-arashiyama-from-the-series-famous-places-of-kyoto.jpg",
    wikimedia_thumb: "/images/artworks/thumb/cherry-blossoms-at-arashiyama-from-the-series-famous-places-of-kyoto.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36515",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 35,
    title: "Yase no Sato",
    title_jp: '',
    series: 'Famous Places of Kyōto' as const,
    series_number: 0,
    year: 1834,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/yase-no-sato.jpg",
    wikimedia_thumb: "/images/artworks/thumb/yase-no-sato.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36516",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
  {
    id: 36,
    title: "Yodogawa",
    title_jp: '',
    series: 'Famous Places of Kyōto' as const,
    series_number: 0,
    year: 1834,
    description: "A station along the Tōkaidō road, rendered in Hiroshige's distinctive ukiyo-e style with bold outlines, delicate color gradations, and a keen observation of travelers and local life.",
    wikimedia_url: "/images/artworks/full/yodogawa.jpg",
    wikimedia_thumb: "/images/artworks/thumb/yodogawa.jpg",
    source_url: "https://www.metmuseum.org/art/collection/search/36517",
    attribution: "Image courtesy of The Metropolitan Museum of Art, Open Access",
    tags: "ukiyo-e,hiroshige,landscape",
    is_featured: false,
    display_order: 99,
  },
]
